# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmfix', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
        migrations.AddField(
            model_name='entry',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='entry',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmfix.Track'),
        ),
    ]
